"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-06 08:03:53.665835
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('planned_classes', sa.Integer(), nullable=True),
    sa.CheckConstraint('planned_classes IS NULL OR planned_classes > 0', name='ck_subjects_planned'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_subjects_department_id'), 'subjects', ['department_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("role IN ('STUDENT', 'MENTOR', 'ADMIN', 'EXAM_CELL')", name='ck_users_role'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('attendance_imports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=8), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('rows_total', sa.Integer(), nullable=False),
    sa.Column('rows_inserted', sa.Integer(), nullable=False),
    sa.Column('rows_updated', sa.Integer(), nullable=False),
    sa.Column('rows_rejected', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('COMPLETED', 'REJECTED')", name='ck_imports_status'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('roll_number', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('semester', sa.SmallInteger(), nullable=False),
    sa.Column('mentor_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('semester BETWEEN 1 AND 12', name='ck_students_semester'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['mentor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('roll_number'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_students_department_id'), 'students', ['department_id'], unique=False)
    op.create_index(op.f('ix_students_mentor_id'), 'students', ['mentor_id'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipient_user_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("severity IN ('INFO', 'WARNING', 'CRITICAL')", name='ck_alerts_severity'),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alerts_recipient', 'alerts', ['recipient_user_id', 'is_read', 'created_at'], unique=False)
    op.create_table('attendance_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('classes_conducted', sa.Integer(), nullable=False),
    sa.Column('classes_attended', sa.Integer(), nullable=False),
    sa.Column('import_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('classes_attended <= classes_conducted', name='ck_attendance_attended_le_conducted'),
    sa.CheckConstraint('classes_attended >= 0', name='ck_attendance_attended_nonneg'),
    sa.CheckConstraint('classes_conducted >= 0', name='ck_attendance_conducted_nonneg'),
    sa.ForeignKeyConstraint(['import_id'], ['attendance_imports.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'subject_id', 'date', name='uq_attendance_student_subject_date')
    )
    op.create_index(op.f('ix_attendance_records_subject_id'), 'attendance_records', ['subject_id'], unique=False)
    op.create_index('ix_attendance_student_date', 'attendance_records', ['student_id', 'date'], unique=False)
    op.create_table('condonation_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('document_path', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('attendance_at_request', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('review_comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('PENDING', 'APPROVED', 'REJECTED', 'WITHDRAWN')", name='ck_condonation_status'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_condonation_requests_student_id'), 'condonation_requests', ['student_id'], unique=False)
    op.create_index('ix_condonation_status', 'condonation_requests', ['status', 'created_at'], unique=False)
    op.create_index('uq_condonation_one_pending', 'condonation_requests', ['student_id', sa.literal_column('COALESCE(subject_id, 0)')], unique=True, postgresql_where=sa.text("status = 'PENDING'"))
    op.create_table('projections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('classes_attended', sa.Integer(), nullable=False),
    sa.Column('classes_conducted', sa.Integer(), nullable=False),
    sa.Column('current_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('projected_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('target_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('trend', sa.String(length=20), nullable=False),
    sa.Column('risk_level', sa.String(length=10), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('recommended_action', sa.Text(), nullable=False),
    sa.Column('classes_required', sa.Integer(), nullable=True),
    sa.Column('recovery_possible', sa.Boolean(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("risk_level IN ('SAFE', 'WARNING', 'CRITICAL', 'NO_DATA')", name='ck_projections_risk'),
    sa.CheckConstraint("trend IN ('IMPROVING', 'STABLE', 'DECREASING', 'INSUFFICIENT_DATA')", name='ck_projections_trend'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_projections_risk', 'projections', ['risk_level'], unique=False)
    op.create_index('uq_projections_overall', 'projections', ['student_id'], unique=True, postgresql_where=sa.text('subject_id IS NULL'))
    op.create_index('uq_projections_subject', 'projections', ['student_id', 'subject_id'], unique=True, postgresql_where=sa.text('subject_id IS NOT NULL'))
    op.create_table('condonation_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('from_status', sa.String(length=10), nullable=True),
    sa.Column('to_status', sa.String(length=10), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['request_id'], ['condonation_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_condonation_events_request_id'), 'condonation_events', ['request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_condonation_events_request_id'), table_name='condonation_events')
    op.drop_table('condonation_events')
    op.drop_index('uq_projections_subject', table_name='projections', postgresql_where=sa.text('subject_id IS NOT NULL'))
    op.drop_index('uq_projections_overall', table_name='projections', postgresql_where=sa.text('subject_id IS NULL'))
    op.drop_index('ix_projections_risk', table_name='projections')
    op.drop_table('projections')
    op.drop_index('uq_condonation_one_pending', table_name='condonation_requests', postgresql_where=sa.text("status = 'PENDING'"))
    op.drop_index('ix_condonation_status', table_name='condonation_requests')
    op.drop_index(op.f('ix_condonation_requests_student_id'), table_name='condonation_requests')
    op.drop_table('condonation_requests')
    op.drop_index('ix_attendance_student_date', table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_subject_id'), table_name='attendance_records')
    op.drop_table('attendance_records')
    op.drop_index('ix_alerts_recipient', table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_students_mentor_id'), table_name='students')
    op.drop_index(op.f('ix_students_department_id'), table_name='students')
    op.drop_table('students')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_table('attendance_imports')
    op.drop_table('users')
    op.drop_index(op.f('ix_subjects_department_id'), table_name='subjects')
    op.drop_table('subjects')
    op.drop_table('departments')
    # ### end Alembic commands ###
